services:
  backend:
    build: 
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php_backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - 8000:8000
    command: php -S 0.0.0.0:8000 -t public

  frontend:
    image: node:18
    container_name: vue_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run serve"
    ports:
      - 80:8080

  db:
    image: mysql:8.0
    restart: always
    ports: 
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    command: --max_allowed_packet=2048M
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: afiliados
      MYSQL_USER: userAfiliadoDB 
      MYSQL_PASSWORD: userAfiliadoDB123
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
